### ISSUE TITLE
No source in repo?

### ISSUE THREAD

**Issue by heinezen** [gregstein/HD-To-TC#1]
Maybe I'm missing something or is there really no source code available for the project?

**Comment by gregstein** [comment]
Hello Heinezen,

Source Code will be published as soon as I Polish it. 

GregStein,

**Comment by heinezen** [comment]
@gregstein Thx, looking forward to that :)

**Comment by gregstein** [comment]
No Problem! Looking forward to sharing this with you guys <3

**Comment by gregstein** [comment]
Source code is released today!
