### ISSUE TITLE
Option to change installation path?

### ISSUE THREAD

**Issue by sarim** [gregstein/HD-To-TC#3]
It'd be nice to have a option to install the game in another path. Some people prefer to install their games in another disk/drive. Is there any special connection with voobly with this path? 

Should be simple to just put a folder selection prompt in the GUI. I can probably contribute the feature if you are too busy :)

**Comment by gregstein** [comment]
I recall attempting to allow users to install in a different location, but Voobly Game diagnostics seem to return path error, and the only path that was acceptable and returned no errors for Voobly was "microsoft games\age of empires ii". I will figure a way for this though. Sure if you want to contribute you are welcome. This app was made for the public and most of the contribution will be considered.

Thank you,

**Comment by sarim** [comment]
Probably there is some registry keys where the path should be registered for voobly to find.

**Comment by gregstein** [comment]
Yes, there is but voobly keeps changing it back to the same path once you join a lobby.
