### ISSUE TITLE
Port some WK feature for convenience 

### ISSUE THREAD

**Issue by sarim** [gregstein/HD-To-TC#4]
Option to install HD hotkeys, Allied Vision, Small Trees (currently included without prompt), Short Walls, Light Grid Terrains, Allied Vision.

These might be easily packed with the tool, new players can jump straight into the game without waiting to download the mods through voobly.

**Comment by gregstein** [comment]
Thank you! I am working on that one.

**Comment by gregstein** [comment]
Your suggestions are now live on release V2: release V2.2 Fixes the issue now: https://github.com/gregstein/HD-To-TC/releases
