### ISSUE TITLE
Screen resolution issue

### ISSUE THREAD

**Issue by RobertoC27** [gregstein/HD-To-TC#5]
Hey man, first of all thanks for making this tool.

Now the issue I'm having is when i launch the game the lobby looks like this: (which is fine, looks the same as compatibility patch) multiplayer looks the same but it doesn't affect gameplay.
**1)**
![image](https://user-images.githubusercontent.com/8262009/36994538-0a85056c-2077-11e8-8e04-7b532ea13465.png) 
**just ignore my poorly stretched image, as screenshot doesn't capture those black bars on the sides**

This issue happens both with and without WK 5.7 selected in Voobly after using this tool.

Now when I'm in game it looks like this with my desktop resolution (2160 x 1440):
**2)**
![image](https://user-images.githubusercontent.com/8262009/36993819-bf45fb12-2074-11e8-8e4c-6fa646168a3a.png)
**This is the actual screenshot, not changed in any way**

It happens with resolutions above (1600 x 900), but if choose it the game looks like this (which is playable but not optimal)
**3)**
![image](https://user-images.githubusercontent.com/8262009/36994205-fd3876b0-2075-11e8-842d-46a6796732c5.png)
**added black bars on top-bottom, trying to replicate what it actually looks in-game**

I have used compatibility patch with  and without WK 5.7 and this issue was not showing. Bars appeared both in main menu and mp lobby but when you start the actual game resolution is working properly.
One thing that caught my eye is how the vertical black bars (screenshot-1) change to horizontal bars in-game (screenshot-2,3).
Here are my screen settings:
![image](https://user-images.githubusercontent.com/8262009/36994557-1c3e7be4-2077-11e8-884e-d2ef4993759a.png)
**4)**
Here is what it looks with the resolution working ok (on Steam)  and what 2 should look like :
![image](https://user-images.githubusercontent.com/8262009/36995379-80c46144-2079-11e8-8b26-49705c0c47a1.png)
**Screenshot without any modification**
edit:
When launching the game using the desktop shortcut (not interacting with voobly in any way) resolution is actually, working.
![image](https://user-images.githubusercontent.com/8262009/36995969-36a474c6-207b-11e8-8f76-fc56459c0638.png)

edit 2:
when launching the exes directly (age2_x1.5 and WK) resolution seems to work fine, starting to believe issue is on Voobly's side.

**Comment by gregstein** [comment]
First off, thank you for this amazing post with illustrations!!

You are correct! The issue lies in the Voobly Game room settings. Just change them to something like this and it should work just fine:

![Voobly Game Room Settings](https://image.prntscr.com/image/ZEh3ELUPSs6HlP7CFzMpIA.png)

Please report back if that actually fixed the problem for you. So the
next release of the patch will auto configure Voobly Game room settings as in the picture above.

Thank you again <3,

**Comment by RobertoC27** [comment]
yep! enabling those settings makes everything run smooth. Thanks for your help and keep up the good work.

**Comment by gregstein** [comment]
Glad to hear that! Thanks for pointing out this issue.
